baseUrl = "https://carolineramond.github.io/FestivalGuitare/"
languageCode = "en-us"
# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "fr"
publishDir = "docs"

[languages]
    [languages.en]
    baseUrl = "https://carolineramond.github.io/FestivalGuitare/en/"
    title="Paris International Guitar Festival"
    [languages.fr]
    baseUrl = "https://carolineramond.github.io/FestivalGuitare/"
    title="Festival International de Guitare de Paris"

# Main menu (fr) ===================

[menu]

[[languages.fr.menu.main]]
    name = "Accueil"
    url  = "#home"
    weight = 1

[[languages.fr.menu.main]]
    name = "Le Festival"
    url  = "#about"
    weight = 2

[[languages.fr.menu.main]]
    name = "Programme"
    url  = "#program"
    weight = 3

[[languages.fr.menu.main]]
    name = "Tarifs & Réservations"
    url  = "#tarifs"
    weight = 4

[[languages.fr.menu.main]]
    name = "Archives / Presse"
    url  = "#archives"
    weight = 5

[[languages.fr.menu.main]]
    name = "Infos Pratiques"
    url  = "#infos"
    weight = 6


# Main menu (en) ===================


[[languages.en.menu.main]]
    name = "Home"
    url  = "#home"
    weight = 1

[[languages.en.menu.main]]
    name = "About"
    url  = "#about"
    weight = 2

[[languages.en.menu.main]]
    name = "Program"
    url  = "#program"
    weight = 3

[[languages.en.menu.main]]
    name = "Prices & Bookings"
    url  = "#tarifs"
    weight = 4

[[languages.en.menu.main]]
    name = "Archives / Press"
    url  = "#archives"
    weight = 5

[[languages.en.menu.main]]
    name = "Information"
    url  = "#infos"
    weight = 6


[params]
    copyright = "Copyright (c) 2018, Association \"Vous avez dit guitare ?\"; all rights reserved."
    telephone = "01.46.80.03.53"
    portable = "06.29.27.20.83"
    reservation = "zozi.com"

    # Format dates with Go's time formatting
    date_format = "January 2, 2006"

[params.homepage]

[languages.fr.homepage]
    background = "img/backgrounds/background2.jpg"
    title = "Festival International de Guitare de Paris"
    subtitle = "XVème édition"
    date = """Du 29 Novembre 2018 au 2 Décembre 2018"""
    place = "Espace Traversière"
    logo="img/logos/logo.png"

[languages.en.homepage]
    background = "img/backgrounds/background2.jpg"
    title = "Paris International Guitar Festival"
    subtitle = "XVth edition"
    date = """From November 29th 2018 to December 2nd 2018"""
    place = "Espace Traversière"
    logo="img/logos/logo.png"

[params.homepage.download]
    label="Télécharger le programme 2018"
    path="img/backgrounds/background.jpg"

[languages.fr.about]
    title="Le Festival"
    text="""<p>
        Depuis 2001, le Festival International de Guitare de Paris met à l'honneur des musiciens...
    </p>
    <p>
        Organisé par l'association <a href="/faq">Vous avez dit guitare ?</a>
        avec le soutien de 
        <a href='http://fr.daddario.com/' target='_blank'>D'addario</a>, 
        <a href='http://www.savarez.fr/' target='_blank'>Savarez</a>, 
        <a href='https://www.guitarreria.eu/' target='_blank'>La Guitarreria</a> 
        et des éditions 
        <a href='https://www.henry-lemoine.com/' target='_blank'>Henry Lemoine</a>, 
        ...
    </p>
    <p>Pour cette édition 2018, nous sommes fiers d'accueillir ...</p>
    """
    facebook="""Pour ne rien manquer du programme et ses actualités, rejoignez-nous sur [Facebook](https://www.facebook.com/Festival-International-de-Guitare-de-Paris-173620507401) !"""

[languages.en.about]
    title="About the Festival"
    text="""<p>
        Since 2001, Paris International Guitar Festival puts the spotlight on musicians from all around the world...
    </p>
    <p>
        It is organized by the association <a href="/faq">Vous avez dit guitare ?</a>
        with the support of
        <a href='http://fr.daddario.com/' target='_blank'>D'addario</a>, 
        <a href='http://www.savarez.fr/' target='_blank'>Savarez</a>, 
        <a href='https://www.guitarreria.eu/' target='_blank'>La Guitarreria</a> 
        and 
        <a href='https://www.henry-lemoine.com/' target='_blank'>Henry Lemoine</a>, 
        ...
    </p>
    <p>For this 2018 session, we are pleased to welcome ...</p>
    """
    facebook="""Dont miss anything about the Festival ! Join us on [Facebook](https://www.facebook.com/Festival-International-de-Guitare-de-Paris-173620507401) !"""


[languages.fr.program]
    title= "Programme"
    default="Programme bientôt disponible"

[languages.en.program]
    title= "Program"
    default="Program soon available"

[languages.fr.tarifs]
    title= "Tarifs & Réservations"

[languages.en.tarifs]
    title= "Prices & Bookings"

[languages.fr.archives]
    title= "Archives / Presse"

[languages.en.archives]
    title= "Archives / Press"

[languages.fr.infos]
    title= "Infos Pratiques"
    place_title="Se rendre au festival"
    place="""Espace Traversière<br>
    15 bis Rue Traversière, 75012 Paris<br>
    Métro Rapée / RER Gare de Lyon
    """
    resa_title="Réservations"
    resa="""Par téléphone au <span class="telephone-number">06.29.27.20.83</span><br>
    ou au <span class="telephone-number">01.46.80.03.53.</span><br>
    Réservation par internet bientôt disponible.
    """
    asso_title="L'Association"
    asso="""Le festival est organisé par l'association <br>"Vous avez dit guitare ?".<br>
    Pour en savoir plus : <a href="/faq">/association</a><br>
    Adhérez à l'association : <a href="/faq">/association</a>
    """

[languages.en.infos]
    title= "Information"
    place_title="How to reach the festival"
    place="""Espace Traversière<br>
    15 bis Rue Traversière, 75012 Paris<br>
    Métro Rapée / RER Gare de Lyon
    """
    resa_title="Bookings"
    resa="""By phone : <span class="telephone-number">06.29.27.20.83</span><br>
    or <span class="telephone-number">01.46.80.03.53.</span><br>
    Online booking soon available.
    """
    asso_title="Our Association"
    asso="""The festival is organized by the association <br>"Vous avez dit guitare ?".<br>
    Learn more : <a href="/faq">/association</a><br>
    Join the association : <a href="/faq">/association</a>
    """

[languages.fr.partners]
    title= "Un grand merci à nos partenaires"

[languages.en.partners]
    title= "Many thanks to our partners"

