baseurl = "https://example.org"
title = "Festival de Guitare de Paris"
languageCode = "en-us"
# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "fr"


# Define the number of posts per page
paginate = 10

[menu]

# Main menu

[[menu.main]]
    name = "Accueil"
    url  = "#home"
    weight = 1

[[menu.main]]
    name = "Le Festival"
    url  = "#about"
    weight = 2

[[menu.main]]
    name = "Programme"
    url  = "#program"
    weight = 3

[[menu.main]]
    name = "Tarifs & Réservations"
    url  = "#tarifs"
    weight = 4

[[menu.main]]
    name = "Archives"
    url  = "#archives"
    weight = 5

[[menu.main]]
    name = "Contact"
    url  = "#contact"
    weight = 6


[params]
    copyright = "Copyright (c) 2018, Association \"Vous avez dit guitare ?\"; all rights reserved."

    # Format dates with Go's time formatting
    date_format = "January 2, 2006"


[params.homepage]
    background = "img/backgrounds/background.jpg"
    title = "Festival de Guitare de Paris"
    subtitle = "XVème édition"
    date = "Novembre 2016"
    place = "Théâtre Adyar"
    logo="img/logos/logo.png"

[params.homepage.download]
    label="Télécharger le programme 2016"
    path="img/backgrounds/background.jpg"

[params.about]
    text="""<p>
        Depuis 2001, le Festival International de Guitare de Paris met à l'honneur des musiciens...
    </p>
    <p>
        Organisé par l'association <a href="/faq">Vous avez dit guitare ?</a>
        avec le soutien de 
        <a href='http://fr.daddario.com/' target='_blank'>D'addario</a>, 
        <a href='http://www.savarez.fr/' target='_blank'>Savarez</a>, 
        <a href='https://www.guitarreria.eu/' target='_blank'>La Guitarreria</a> 
        et des éditions 
        <a href='https://www.henry-lemoine.com/' target='_blank'>Henry Lemoine</a>, 
        ...
    </p>
    <p>Pour cette édition 2016, nous sommes fiers d'accueillir ...</p>
    """
    facebook="https://www.facebook.com/Festival-International-de-Guitare-de-Paris-173620507401/"


[params.program]
    title= "Programme"

[params.tarifs]
    title= "Tarifs & Réservation"

[params.archives]
    title= "Archives"