baseUrl = "https://carolineramond.github.io/FestivalGuitare/"
languageCode = "en-us"
# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "fr"
publishDir = "docs"

[languages]
    [languages.en]
    baseUrl = "https://carolineramond.github.io/FestivalGuitare/en/"
    title="Paris International Guitar Festival"
    [languages.fr]
    baseUrl = "https://carolineramond.github.io/FestivalGuitare/"
    title="Festival International de Guitare de Paris"

# Main menu (fr) ===================

[menu]

[[languages.fr.menu.main]]
    name = "Accueil"
    url  = "#home"
    weight = 1

[[languages.fr.menu.main]]
    name = "Edito"
    url  = "#about"
    weight = 2

[[languages.fr.menu.main]]
    name = "Programme"
    url  = "#program"
    weight = 3

[[languages.fr.menu.main]]
    name = "Concours"
    url  = "#concours"
    weight = 4

[[languages.fr.menu.main]]
    name = "Archives / Presse"
    url  = "#archives"
    weight = 5

[[languages.fr.menu.main]]
    name = "Tarifs & Réservations"
    url  = "#tarifs"
    weight = 6

[[languages.fr.menu.main]]
    name = "Infos Pratiques"
    url  = "#infos"
    weight = 7


# Main menu (en) ===================


[[languages.en.menu.main]]
    name = "Home"
    url  = "#home"
    weight = 1

[[languages.en.menu.main]]
    name = "Editorial"
    url  = "#about"
    weight = 2

[[languages.en.menu.main]]
    name = "Program"
    url  = "#program"
    weight = 3

[[languages.en.menu.main]]
    name = "Competition"
    url  = "#concours"
    weight = 4

[[languages.en.menu.main]]
    name = "Archives / Press"
    url  = "#archives"
    weight = 5

[[languages.en.menu.main]]
    name = "Prices & Booking"
    url  = "#tarifs"
    weight = 6

[[languages.en.menu.main]]
    name = "Information"
    url  = "#infos"
    weight = 6


[params]
    copyright = "Copyright (c) 2018, Association \"Vous avez dit guitare ?\"; all rights reserved."
    telephone = "01.46.80.03.53"
    portable = "06.29.27.20.83"
    mail = "festivalguitareparis@gmail.com"
    reservation = "zozi.com"

    # Format dates with Go's time formatting
    date_format = "January 2, 2006"

[params.homepage]

[languages.fr.homepage]
    background = "img/backgrounds/background2.jpg"
    title = "Festival International de Guitare de Paris"
    subtitle = "XVème édition"
    date = """Du 29 Novembre 2018 au 2 Décembre 2018"""
    place = "Espace Traversière"
    logo="img/logos/logo.png"
    concours="Premier Concours International de Guitare \"Alberto Ponce\""

[languages.en.homepage]
    background = "img/backgrounds/background2.jpg"
    title = "Paris International Guitar Festival"
    subtitle = "XVth edition"
    date = """From November 29th 2018 to December 2nd 2018"""
    place = "Espace Traversière"
    logo="img/logos/logo.png"
    concours="First Paris International Guitar Competition \"Alberto Ponce\""

[params.homepage.download]
    label="Télécharger le programme 2018"
    path="img/backgrounds/background.jpg"

[languages.fr.about]
    title="Edito"
    text="""<p>
        Cher(e)s ami(e)s,
    </p>
    <p align="justify">
        C’est avec un immense plaisir que nous nous retrouvons après une année d’interruption. Cette quinzième édition du Festival International de Guitare de Paris, qui aura lieu du 29 novembre au 2 décembre 2018, sera fidèle à l’esprit des quatorze premières : une programmation variée avec comme seule et unique ambition l’exigence artistique. 
    </p>
    <p align="justify">
        Cependant, cette quinzième édition ne ressemblera pas exactement aux autres. Tout d’abord, le Festival aura lieu pour la première fois cette année au théâtre Traversière (XII). Nous espérons que vous aussi apprécierez cette salle, nouvel écrin pour notre instrument. Ensuite, et c’est là un changement majeur, cette édition s’enrichira d’un concours international de guitare : le premier Concours International de Guitare « Alberto Ponce » de Paris. Cet événement permettra de mettre en lumière les talents de demain et donnera un souffle artistique et humain tout particulier à notre festival.
    </p>
    <p align="justify">
        Nous espérons modestement qu’avec l’organisation de ce concours, la guitare à Paris retrouvera, davantage encore, la place qu’elle avait du temps de Robert J. Vidal, figure tutélaire sans qui le Festival de Guitare de Paris ne serait pas ce qu’il est.
    </p>
    <p align="justify">
        Ce quinzième festival et tout spécialement la soirée du jeudi seront dédiés à la mémoire d’Isabel Gomez qui nous a quittés cette année. Isabel a illuminé le monde de la guitare par sa gentillesse, sa générosité hors du commun et son indéfectible passion pour notre instrument. Le Festival International de Guitare de Paris lui doit son existence.
    </p>
    <p align="justify">
        Ainsi durant quatre jours, concerts, concours, master-class, conférences vous donneront à entendre, nous l’espérons, le meilleur de la guitare.
        Nous tenons à remercier chaleureusement tous nos partenaires, 
        <a href='https://www.guitarreria.eu/' target='_blank'>La Guitarreria</a> , 
        <a href='https://www.henry-lemoine.com/' target='_blank'>les éditions Henry Lemoine</a>,
        <a href='http://www.savarez.fr/' target='_blank'>les cordes Savarez</a>, 
        <a href='http://fr.daddario.com/' target='_blank'>les cordes D'addario</a>, 
        qui ont toujours cru en nous, même dans les moments difficiles.
    </p>
    <p align="justify">
        Nous vous attendons impatiemment au théâtre Traversière à la fin du mois de novembre, Bonne rentrée à tous!
    </p>
    <p align="right">
        L’équipe du Festival International de Guitare de Paris.
    </p>
    """

    facebook="""Pour ne rien manquer du programme et ses actualités, rejoignez-nous sur <a href ='https://www.facebook.com/Festival-International-de-Guitare-de-Paris-173620507401' target='_blank'>Facebook !</a>"""

[languages.en.about]
    title="Editorial"
    text="""<p>
        Dear friends,
    </p>
    <p align="justify">
        It is a real pleasure to meet again after a one year break. This fifteenth edition of the Paris International Guitar Festival will take place from November 29th to December 2nd 2018. We want it to stay true to the spirit of the fourteen first editions with a varied program, and artistical excellence for only ambition.
    </p>
    <p align="justify">
        However, this fifteenth edition will not be just like the others. To begin with, the Festival will take place for the first time at the \"théâtre Traversière\" (XII). We hope you will enjoy this new venue as a setting for our instrument.
        Then, a major change is coming as an international guitar competition will enrich the festival: the first Paris International Guitar Competition \"Alberto Ponce\". This event will shed light on tomorrow's talents and bring a breath of fresh air to our festival.
    </p>
    <p align="justify">
        We modestly hope the organization of this competition will help guitar in Paris to get back the importance it had in the days of Robert J. Vidal. He was a figure without which the Paris Guitar Festival wouldn't be what it is today.
    </p>
    <p align="justify">
        We would like to dedicate this fifteenth festival - and particularly the thursday evening - to Isabel Gomez, who passed away this year. Isabel illuminated the guitar world with her kindness, her incredible generosity, and her unfailing passion for our instrument. The Paris Guitar Festival ows her its existence.
    </p>
    <p align="justify">
        Thereby, we hope that these four days of concerts, competition, master-classes will bring you the best of guitar.
        We would like to thank warmly all of our partners,
        <a href='https://www.guitarreria.eu/' target='_blank'>La Guitarreria</a> , 
        <a href='https://www.henry-lemoine.com/' target='_blank'>the Henry Lemoine editions</a>,
        <a href='http://www.savarez.fr/' target='_blank'>the Savarez strings</a>, and the
        <a href='http://fr.daddario.com/' target='_blank'>the D'addario strings</a>.
        They have always believed in us, even in the most difficult moments.
    </p>
    <p align="justify">
        We look forward to see you at the \"théâtre Traversière\" in the end of November. Enjoy the new school year !
    </p>
    <p align="right">
        Paris International Guitar Festival team.
    </p>
    """
    facebook="""Dont miss anything about the Festival ! Join us on [Facebook](https://www.facebook.com/Festival-International-de-Guitare-de-Paris-173620507401) !"""


[languages.fr.program]
    title= "Programme"
    default="Programme bientôt disponible"
    text="""<p>Cette année, nous sommes fiers d'accueillir <strong>Thibaut Garcia</strong>, <strong>Alfonso Carpio Fernàndez & Marco \"el curandero\"</strong>, <strong>José Galvez</strong>, <strong>Isidoro Fernandez Roman</strong>, <strong>Rolf Lislevand</strong>, <strong>Alvarro Pierri</strong>, <strong>Juan Falù</strong>, le <strong>Take4 Quartet</strong> et <strong>Lorenzo Micheli</strong>. 
    </p>
    <p>
    Pour nos \"Concerts en +\", nous accueillerons également le <strong>Quatuor Bergamasque</strong>, <strong>Raphaël Feuillâtre</strong> et <strong>Cyprien N'Tsaï</strong>. Sans oublier les \"Guitares à Suivre\": <strong>Clément Mengelle</strong>, <strong>Johan Smith</strong> et <strong>Paul Sun</strong>.
    </p>
    """

[languages.en.program]
    title= "Program"
    default="Program soon available"
    text="""<p>This year, we are proud to welcome <strong>Thibaut Garcia</strong>, <strong>Alfonso Carpio Fernàndez & Marco "el curandero"</strong>, <strong>José Galvez</strong>, <strong>Isidoro Fernandez Roman</strong>, <strong>Rolf Lislevand</strong>, <strong>Alvarro Pierri</strong>, <strong>Juan Falù</strong>, the <strong>Take4 Quartet</strong> and <strong>Lorenzo Micheli</strong>. 
    </p>
    <p>
    For our extra concerts (\"Concerts en + \"), we will also welcome the <strong>Quatuor Bergamasque</strong>, <strong>Raphaël Feuillâtre</strong> and <strong>Cyprien N'Tsaï</strong>. To finish with, let's not forget the new talents of \"Guitares à Suivre\": <strong>Clément Mengelle</strong>, <strong>Johan Smith</strong> and <strong>Paul Sun</strong>.
    </p>
    """

[languages.fr.concours]
    title= """Concours International de Guitare 'Alberto Ponce' <br> Première édition"""
    inscription="Bulletin d'inscription"
    reglement="Règlement du concours"
    infos="""Informations complémentaires par mail à 
    <span class="telephone-number">festivalguitareparis@gmail.com</span> 
    ou par téléphone au <span class="telephone-number">06.29.27.20.83</span> / 
    <span class="telephone-number">01.46.80.03.53</span>
    """
    [[languages.fr.concours.item]]
        title="Eliminatoires"
        date="""<p>Mercredi 28 Novembre<br>
            <strong>9h-13h / 14h30-19h</strong></p>
            <p>Jeudi 29 Novembre<br>
            <strong>9h-13h / 14h30-19h</strong></p>
        """
    [[languages.fr.concours.item]]
        title="Demi-Finale"
        date="""<p>Vendredi 30 Novembre<br>
            <strong>9h-17h</strong></p>
        """
    [[languages.fr.concours.item]]
        title="Finale"
        date="""<p>Samedi 1er Décembre<br>
            <strong>20h</strong></p>
        """

[languages.en.concours]
    title= """International Guitar Competition 'Alberto Ponce' <br> First edition"""
    inscription="Application form"
    reglement="Competition rules"
    infos="""Additional information by mail at 
    <span class="telephone-number">festivalguitareparis@gmail.com</span> 
    or by phone at <span class="telephone-number">06.29.27.20.83</span> / 
    <span class="telephone-number">01.46.80.03.53</span>
    """
    [[languages.en.concours.item]]
        title="Elimination Round"
        date="""<p>Wd November 28th<br>
            <strong>9h-13h / 14h30-19h</strong></p>
            <p>Th November 29th<br>
            <strong>9h-13h / 14h30-19h</strong></p>
        """
    [[languages.en.concours.item]]
        title="Semi-Finale"
        date="""<p>Fr November 30th<br>
            <strong>9h-17h</strong></p>
        """
    [[languages.en.concours.item]]
        title="Finale"
        date="""<p>Sa December 1st<br>
            <strong>20h</strong></p>
        """

[languages.fr.tarifs]
    title= "Tarifs & Réservations"
    infos="""Informations & réservations par mail à 
    <span class="telephone-number">festivalguitareparis@gmail.com</span> 
    ou par téléphone au <span class="telephone-number">06.29.27.20.83</span> / 
    <span class="telephone-number">01.46.80.03.53</span>
    """

    [[languages.fr.tarifs.item]]
        title="Concerts"
        prices="""Plein tarif - <strong>25€</strong><br>
            Tarif réduit - <strong>19€</strong>
        """
        resa=true

    [[languages.fr.tarifs.item]]
        title="Pass 3 Concerts"
        prices="""Plein tarif - <strong>60€</strong><br>
            Tarif réduit - <strong>51€</strong>
        """
        resa=true

    [[languages.fr.tarifs.item]]
        title="Pass 4 Concerts"
        prices="""Plein tarif - <strong>78€</strong><br>
            Tarif réduit - <strong>68€</strong>
        """
        resa=true

    [[languages.fr.tarifs.item]]
        title="Concerts en +"
        prices="""Tarif unique - <strong>12€</strong>"""
        infos="Sans réservation"


    [[languages.fr.tarifs.item]]
        title="Master Class"
        prices="""Participant - <strong>40€</strong><br>
        Auditeur - <strong>10€</strong>"""
        infos="""Participant - Réservation par mail/téléphone<br>
        Auditeur - Sans réservation
        """

    [[languages.fr.tarifs.item]]
        title="Concert \"Guitares à suivre\""
        prices=""""""
        infos="""Entrée libre
        """


    [[languages.fr.tarifs.item]]
        title="Salon de lutherie"
        prices=""""""
        infos="""Entrée libre
        """

[languages.en.tarifs]
    title= "Prices & Bookings"
    infos="""Additional information & booking by mail at 
    <span class="telephone-number">festivalguitareparis@gmail.com</span> 
    or by phone at <span class="telephone-number">06.29.27.20.83</span> / 
    <span class="telephone-number">01.46.80.03.53</span>
    """

    [[languages.en.tarifs.item]]
        title="Concerts"
        prices="""Full price - <strong>25€</strong><br>
            Reduced price - <strong>19€</strong>
        """
        resa=true

    [[languages.en.tarifs.item]]
        title="3 Concerts Pass"
        prices="""Full price - <strong>60€</strong><br>
            Reduced price - <strong>51€</strong>
        """
        resa=true

    [[languages.en.tarifs.item]]
        title="4 Concerts Pass"
        prices="""Full price - <strong>78€</strong><br>
            Reduced price - <strong>68€</strong>
        """
        resa=true

    [[languages.en.tarifs.item]]
        title="Extra Concerts (\"Concerts en +\")"
        prices="""Price - <strong>12€</strong>"""
        infos="No booking needed"


    [[languages.en.tarifs.item]]
        title="Master Class"
        prices="""Player - <strong>40€</strong><br>
        Audience - <strong>10€</strong>"""
        infos="""Participant - Booking by mail/phone<br>
        Auditeur - No booking needed
        """

    [[languages.en.tarifs.item]]
        title="Young talents concert (\"Guitares à suivre\")"
        prices=""""""
        infos="""Free entrance
        """

    [[languages.en.tarifs.item]]
        title="Lute-making exhibition"
        prices=""""""
        infos="""Free entrance
        """

[languages.fr.archives]
    title= "Archives / Presse"

[languages.en.archives]
    title= "Archives / Press"

[languages.fr.infos]
    title= "Infos Pratiques"
    place_title="Se rendre au festival"
    place="""Espace Traversière<br>
    15 bis Rue Traversière, 75012 Paris<br>
    Métro Rapée / RER Gare de Lyon
    """
    resa_title="Réservations"
    resa="""Par mail à <span class="telephone-number">festivalguitareparis@gmail.com</span>.<br>
    Par téléphone au <span class="telephone-number">06.29.27.20.83</span><br>
    ou au <span class="telephone-number">01.46.80.03.53</span><br>
    Réservation par internet bientôt disponible.
    """
    asso_title="L'Association"
    asso="""Le festival est organisé par l'association<br>\"Vous avez dit guitare ?\""""
    asso_link="En savoir plus / Adhérer à l'association"

[languages.en.infos]
    title= "Information"
    place_title="How to reach the festival"
    place="""Espace Traversière<br>
    15 bis Rue Traversière, 75012 Paris<br>
    Métro Rapée / RER Gare de Lyon
    """
    resa_title="Bookings"
    resa="""By phone : <span class="telephone-number">06.29.27.20.83</span><br>
    or <span class="telephone-number">01.46.80.03.53.</span><br>
    Online booking soon available.
    """
    asso_title="Our Association"
    asso="""The festival is organized by the association<br>\"Vous avez dit guitare ?\""""
    asso_link="Learn more / Join the association"

[languages.fr.partners]
    title= "Un grand merci à nos partenaires"

[languages.en.partners]
    title= "Many thanks to our partners"

[languages.fr.asso]
    title= "Association \"Vous avez dit guitare ?\""
    text= "coucou les ptits potes"

[languages.en.asso]
    title= "Association \"Vous avez dit guitare ?\""
    text= "coucou les ptits potes"


